# Generated by Django 4.2.7 on 2026-03-08 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('platform_post_id', models.CharField(db_index=True, max_length=200)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0, help_text='(likes+shares+comments)/reach * 100')),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='brands.brand')),
                ('post_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='brands.postlog')),
            ],
            options={
                'verbose_name': 'Post Analytics',
                'verbose_name_plural': 'Post Analytics',
                'ordering': ['-snapshot_at'],
                'indexes': [models.Index(fields=['brand', 'platform', 'snapshot_at'], name='analytics_p_brand_i_ad91a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='BrandAnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('platform', models.CharField(max_length=20)),
                ('total_posts', models.PositiveIntegerField(default=0)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_reach', models.PositiveIntegerField(default=0)),
                ('avg_engagement_rate', models.FloatField(default=0.0)),
                ('best_post_id', models.CharField(blank=True, max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='brands.brand')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('brand', 'date', 'platform')},
            },
        ),
    ]
