# Generated by Django 4.2.7 on 2026-03-08 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text='Type of content to generate: education, programming, devotional, etc.', max_length=50)),
                ('topic_hint', models.CharField(blank=True, help_text='Optional topic hint for the AI generator. Leave blank for full AI creativity.', max_length=300)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('done', 'Done'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='brands.brand')),
                ('post_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_post', to='brands.postlog')),
            ],
            options={
                'verbose_name': 'Scheduled Post',
                'verbose_name_plural': 'Scheduled Posts',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='calendar_sc_status_0d671e_idx'), models.Index(fields=['brand', 'scheduled_at'], name='calendar_sc_brand_i_ddd1d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostingWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('post_hour', models.IntegerField(help_text='Hour in 24h format (0–23)')),
                ('post_minute', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_windows', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Posting Window',
                'verbose_name_plural': 'Posting Windows',
                'ordering': ['day_of_week', 'post_hour'],
                'unique_together': {('brand', 'day_of_week', 'post_hour')},
            },
        ),
    ]
