# Generated by Django 4.2.7 on 2026-03-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=800, unique=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(db_index=True, default='general', help_text='e.g. education, programming, forex, ai_tech', max_length=50)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'News Item',
                'verbose_name_plural': 'News Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_used', 'created_at'], name='news_newsit_categor_447553_idx')],
            },
        ),
    ]
