# Generated by Django 4.2.7 on 2026-03-08 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(help_text='Used as identifier in tasks', max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tone', models.CharField(choices=[('inspirational', 'Inspirational'), ('educational', 'Educational'), ('devotional', 'Devotional'), ('professional', 'Professional'), ('casual', 'Casual'), ('motivational', 'Motivational')], default='educational', max_length=30)),
                ('content_type', models.CharField(choices=[('education', 'Education'), ('programming', 'Programming'), ('devotional', 'Devotional'), ('forex', 'Forex / Trading'), ('motivation', 'Motivation'), ('news', 'News'), ('general', 'General')], default='general', max_length=30)),
                ('custom_voice_prompt', models.TextField(blank=True, help_text='Extra instructions for AI when generating content for this brand.')),
                ('hashtags', models.TextField(blank=True, help_text='Default hashtags (comma-separated). e.g. #EduImpact,#LearnEveryDay')),
                ('post_to_facebook', models.BooleanField(default=True)),
                ('post_to_x', models.BooleanField(default=True)),
                ('facebook_page_id', models.CharField(blank=True, max_length=100)),
                ('facebook_access_token', models.TextField(blank=True)),
                ('x_api_key', models.CharField(blank=True, max_length=200)),
                ('x_api_secret', models.CharField(blank=True, max_length=200)),
                ('x_access_token', models.CharField(blank=True, max_length=200)),
                ('x_access_token_secret', models.CharField(blank=True, max_length=200)),
                ('posts_per_day', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('x', 'X (Twitter)'), ('both', 'Both Platforms')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed'), ('blocked', 'Blocked by Safety'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('post_text', models.TextField()),
                ('caption', models.TextField(blank=True)),
                ('hashtags_used', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('platform_post_id', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_logs', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Post Log',
                'verbose_name_plural': 'Post Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'status'], name='brands_post_brand_i_9de4ec_idx'), models.Index(fields=['scheduled_at'], name='brands_post_schedul_7a7f54_idx')],
            },
        ),
    ]
